FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache ffmpeg python3 make g++

COPY package.json tsconfig.json ./

RUN npm install --ignore-scripts --legacy-peer-deps

CMD ["npx", "ts-node", "--transpile-only", "src/index.ts"]
